Traceback (most recent call last):
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\adnegrau\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from azureml.core import Workspace
from getpass import getpass
import pandas as pd
import openai
import mlflow
import os
azure_openai_key = os.environ["azure_openai_key"]
azure_aoai_endpoint = os.environ["AZURE_OPENAI_ENDPOINT"]
aoi_deployment_name = os.environ["AZURE_OPENAI_CHAT_DEPLOYMENT_NAME"]

os.environ.setdefault("OPENAI_API_KEY", azure_openai_key)
os.environ.setdefault("OPENAI_API_BASE", azure_aoai_endpoint)
os.environ.setdefault("OPENAI_API_VERSION", "2023-05-15")
os.environ.setdefault("OPENAI_API_TYPE", "azure")
os.environ.setdefault("OPENAI_DEPLOYMENT_NAME", aoi_deployment_name)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn[1], line 7[0m
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mmlflow[39;00m
[0;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[1;32m----> 7[0m azure_openai_key [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43menviron[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mazure_openai_key[39;49m[38;5;124;43m"[39;49m[43m][49m
[0;32m      8[0m azure_aoai_endpoint [38;5;241m=[39m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124mAZURE_OPENAI_ENDPOINT[39m[38;5;124m"[39m]
[0;32m      9[0m aoi_deployment_name [38;5;241m=[39m os[38;5;241m.[39menviron[[38;5;124m"[39m[38;5;124mAZURE_OPENAI_CHAT_DEPLOYMENT_NAME[39m[38;5;124m"[39m]

File [1;32m<frozen os>:685[0m, in [0;36m__getitem__[1;34m(self, key)[0m

[1;31mKeyError[0m: 'azure_openai_key'

